{{- if not (and (not .Values.postgres.enabled) .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cdmad-vdb.fullname" . }}
  labels:
    {{- include "cdmad-vdb.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgres.enabled }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  {{- else }}
  POSTGRES_PASSWORD: {{ .Values.externalDatabase.password | quote }}
  {{- end }}
{{- end }}
